# Secure Woodpecker CI Pipeline using Kaniko (No Privileged Access Required)
# This is more secure than using the Docker plugin

when:
  event:
    - push
    - pull_request

steps:
  # Install dependencies
  install:
    image: node:20-alpine
    commands:
      - npm ci
    when:
      event:
        - push
        - pull_request

  # Run linting
  lint:
    image: node:20-alpine
    commands:
      - npm run lint
    depends_on:
      - install
    when:
      event:
        - push
        - pull_request

  # Run tests
  test:
    image: node:20-alpine
    commands:
      - npm run test
    depends_on:
      - install
    when:
      event:
        - push
        - pull_request

  # Build the application
  build:
    image: node:20-alpine
    commands:
      - npm run build
    depends_on:
      - install
    when:
      event:
        - push
        - pull_request

  # Build and push Docker image using Kaniko (secure, no privileged access)
  docker-build:
    image: gcr.io/kaniko-project/executor:latest
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - mkdir -p /kaniko/.docker
      - echo "{\"auths\":{\"ghcr.io\":{\"auth\":\"$(echo -n $${DOCKER_USERNAME}:$${DOCKER_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
      - /kaniko/executor
        --context=.
        --dockerfile=Dockerfile
        --destination=ghcr.io/colecoffman/NodeBase:${CI_COMMIT_SHA:0:7}
        --destination=ghcr.io/colecoffman/NodeBase:latest
        --cache=true
        --cache-ttl=24h
        --snapshot-mode=redo
        --use-new-run
    depends_on:
      - build
    when:
      event:
        - push
      branch:
        - main
        - master
